-- Seed: magias iniciais
insert into spells (name, type, circle, school, execution, range, duration, target, resistance, publication, effect, amplifiers, is_public, created_by)
values
(
  'Bênção',
  'Divina',
  1,
  'Encantamento',
  'Padrão',
  'Curto',
  'Cena',
  'Você e aliados em alcance',
  '—',
  'Tormenta20, p. 183',
  'Você e todos os aliados em alcance ficam sob efeito de bênção. Criaturas abençoadas recebem +1 em rolagens de ataque e salvaguardas.',
  '[{"cost": 2, "effect": "O bônus de bênção aumenta para +2."}, {"cost": 2, "effect": "O alcance aumenta para médio."}, {"cost": 5, "effect": "Você pode lançar esta magia como ação livre."}]',
  true,
  null
),
(
  'Curar Ferimentos',
  'Divina',
  1,
  'Transmutação',
  'Padrão',
  'Toque',
  'Instantânea',
  '1 criatura',
  '—',
  'Tormenta20, p. 186',
  'O alvo recupera 1d8 + modificador de Sabedoria em pontos de vida. Em mortos-vivos, em vez de curar, a magia causa o mesmo valor de dano (sem resistência).',
  '[{"cost": 2, "effect": "A cura aumenta em +1d8."}, {"cost": 5, "effect": "Você pode lançar esta magia com alcance curto."}]',
  true,
  null
),
(
  'Névoa',
  'Arcana',
  1,
  'Ilusão',
  'Padrão',
  'Médio',
  'Sustentada',
  'Esfera com 3m de raio',
  '—',
  'Tormenta20, p. 196',
  'Uma névoa espessa surge em um ponto que você determina dentro do alcance. A névoa concede camuflagem total a todas as criaturas dentro da área. Ventos fortes (naturais ou mágicos) dissipam a névoa instantaneamente.',
  '[{"cost": 2, "effect": "Aumenta a área para uma esfera com 6m de raio."}, {"cost": 2, "effect": "Aumenta o alcance para longo."}, {"cost": 5, "effect": "Você pode mover a névoa até 6m por rodada como ação livre."}]',
  true,
  null
),
(
  'Comando',
  'Universal',
  1,
  'Encantamento',
  'Padrão',
  'Curto',
  'Rodada',
  '1 criatura',
  'Vontade anula',
  'Tormenta20, p. 185',
  'Você ordena um alvo com uma única palavra (exemplos: fuja, caia, para). O alvo fica desprevenido por um instante e deve seguir a ordem na sua próxima ação. Criaturas imunes a encantamentos ou que não entendam o idioma são automaticamente imunes.',
  '[{"cost": 2, "effect": "Você pode lançar em um alvo adicional."}, {"cost": 3, "effect": "A duração aumenta para cena."}]',
  true,
  null
),
(
  'Despedaçar',
  'Arcana',
  2,
  'Transmutação',
  'Padrão',
  'Curto',
  'Instantânea',
  '1 objeto ou criatura',
  'Fortitude parcial',
  'Tormenta20, p. 187',
  'Você destrói completamente um objeto não mágico de até 5 kg, ou causa 4d6 de dano de impacto em uma criatura. Fortitude reduz o dano à metade.',
  '[{"cost": 2, "effect": "Aumenta o dano em +2d6."}, {"cost": 2, "effect": "Pode afetar objetos mágicos (CD +5 para a salvaguarda)."}]',
  true,
  null
),
(
  'Futuro Melhor',
  'Divina',
  2,
  'Adivinhação',
  'Padrão',
  'Pessoal',
  'Cena',
  'Você',
  '—',
  'Tormenta20, p. 191',
  'Você vislumbra os possíveis futuros imediatos. Uma vez antes do fim da cena, você pode rolar dois dados para qualquer teste e usar o melhor resultado.',
  '[{"cost": 3, "effect": "Você pode usar o benefício duas vezes."}, {"cost": 5, "effect": "O alcance aumenta para toque; você pode afetar um aliado."}]',
  true,
  null
);
